---
- name: Install git and update the tree
  become: true
  apt: pkg=git state=present update_cache=yes

- name: Install dependencies
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  tags: nvm

- name: Check for nvm
  stat: path=~/.nvm
  register: nvm_path

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }} accept_hostkey=True
  tags: nvm
  when: not nvm_path.stat.exists

- name: Source nvm
  lineinfile: >
    state=present
    dest={{ nvm.profile_file }}
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Check for current node version
  command: ~/.nvm/versions/node/v{{ nvm.node_version }}/bin/node -v
  register: nvm_node_version
  ignore_errors: yes
  changed_when: false

- name: Install node v{{ nvm.node_version }}
  shell: source ~/.profile && nvm install {{ nvm.node_version }}
  args:
    executable: /bin/bash
  register: installation_output
  tags:
    - nvm
  when: nvm_node_version.get('stdout', 'anything that isnt evaluating').find(nvm.node_version) == -1

- name: Set default node version to installed node
  shell: source ~/.profile && nvm alias default {{ nvm.node_version }}
  args:
    executable: /bin/bash
  register: defaultversion_output
  tags: nvm
  when: nvm_node_version.get('stdout', 'anything that isnt evaluating').find(nvm.node_version) == -1

- name: Search npm binary
  command: which ~/.nvm/versions/node/v{{ nvm.node_version }}/bin/npm
  register: npm_executable
  ignore_errors: yes
  changed_when: false

- name: Install general package
  npm: name={{ item }} global=yes executable={{ npm_executable.stdout }}
  with_items: nvm.packages
